### ISSUE TITLE
Alias always generates same stack

### ISSUE THREAD

**Issue by xavicolomer** [HyperBrain/serverless-aws-alias-example#1]
Hi there,

`Serverless version: 1.17`

For some reason I am always generating the same stack no matter what Alias I put on. I followed the installation instructions and it seems the Alias plugin is giving some feedback while deploying, but its always deploying / overwriting the same content with the same endpoints

I created first the first stage deploy
`serverless deploy` 

And then I tried to create aliases for v1
`serverless deploy --alias v1`

and v2
`serverless deploy --alias v2`

But I always end up overwriting the API Gateway, Lambdas and everything
`POST - https://{same_endpoint}.execute-api.eu-west-1.amazonaws.com/...`

Any suggestion?

**Comment by HyperBrain** [comment]
Check if your Lambda versions are tagged with aliases and you have 2 stages in APIG (v1 + v2) after deploying the aliases.

You should be able to reach all aliased apis with `https://{same_endpoint}.execute-api.eu-west-1.amazonaws.com/<alias_here>/`.

You can find the different versions of your Lambdas in the AWS Lambda console, select a Lambda and the aliases (including the stage alias) should show up in the "Qualifier" dropdown.

**Comment by xavicolomer** [comment]
Ok so far I found out:

1. In my lambda console I only have one version of the lambdas, I would expect to have one version per alias, is that right?

2. Reading your<alias_here> I understand that API Gateway should contain as many initial resources as aliases and then the master API hanging from there although it doesn't, but this is just a guess

```
/
  /v1
    /my
      /master
        /api
  /v2
    /my
      /master
        /api 
```




3. In my .serverless folder I have 2 new files:

cloudformation-template-update-alias-stack.json
cloudformation-template-create-alias-stack.json

Both containing information only about the last alias deployed, in this case v2

Is that useful? How can I provide you with more info?

**Comment by xavicolomer** [comment]
Ops sorry I posted this on the wrong project.

**Comment by HyperBrain** [comment]
No problem :)
