### ISSUE TITLE
Compatibility with shared API GW

### ISSUE THREAD

**Issue by a-panickar** [HyperBrain/serverless-aws-alias-example#3]
@HyperBrain Thanks for the plugin.

I see that you had mentioned this plugin wouldn't work with the [PR](https://github.com/serverless/serverless/pull/3934) that enables reusing existing API GW's across multiple sls stacks.

Do you plan on updating the plugin to support that model anytime soon? Also, do you have any short-term recommendations or workarounds in the interim?

**Comment by HyperBrain** [comment]
@abhilash80 Can you move the issue to the plugin repo? I think you accidentially used the examples project as target 😃

**Comment by a-panickar** [comment]
You are right... I apologize for the goof up.
